Repository containrrr/watchtower, pull requests merged in 2019-04, with the labels that each got.

#116 github/v2tec/watchtower#114 adding if statement to accept the oneshot…
  README.md
  main.go
Labels: enhancement

#282 check if schedule len > 0 to prevent collisions
  main.go
Labels: bug

#283 Add Dockerfile.self-contained
  Dockerfile.self-contained
Labels: Priority: Low, Status: Revision Needed, Type: Enhancement

#284 add tests for check action, resolve wt cleanup bug
  actions/actions_suite_test.go
  actions/check.go
  container/container.go
  main.go
Labels: Priority: High, Status: Review Needed, Type: Bug
